export default {
    SAVE_COMMENT: "SAVE_COMMENT_ACTION",
    ADD_MOVIE_TO_FAVOURITES: "ADD_MOVIE_TO_FAVOURITES_ACTION",
    DELETE_MOVIE_FROM_FAVOURITES: "DELETE_MOVIE_FROM_FAVOURITES_ACTION",
    ADD_NEW_ARRIVAL: "ADD_NEW_ARRIVAL_ACTION",

    GET_SERIESES: "GET_SERIESES_ACTION",
    GET_SERIESES_PENDING: "GET_SERIESES_PENDING",
    GET_SERIESES_SUCCESS: "GET_SERIESES_SUCCESS",
    GET_SERIESES_FAILEURE: "GET_SERIESES_FAILEURE_ACTION"  
}